# Generated by Django 5.0.8 on 2024-09-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_delete_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stste',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
