# Generated by Django 5.0.8 on 2024-09-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_stste_order_state_rename_zip_order_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oreder_id',
            new_name='order_id',
        ),
    ]
