# Generated by Django 5.2.6 on 2025-09-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
