# Generated by Django 4.2.23 on 2025-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_orderupdate_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_descs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
