# Generated by Django 4.2.23 on 2025-09-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_quantities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
