# Generated by Django 4.2.23 on 2025-09-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_item_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_descs',
        ),
    ]
