# Generated by Django 4.2.23 on 2025-09-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_order_product_descs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
